spring.application.name=SocialMedia
spring.datasource.username=entity_relationships_user
spring.datasource.password=S1r1yZxuVB81KicJYjjlLYGGqbctWdoB
spring.datasource.url=jdbc:postgresql://dpg-db1nnb0u01pc73fafv1g-a.oregon-postgres.render.com/entity_relationships?currentSchema=public
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
server.error.include-message=always