spring.application.name=SocialMedia
spring.datasource.username=social_vymp_user
spring.datasource.password=6oSosQpQNcR1AsaFzs6vZIaGAmP8wQ3T
spring.datasource.url=jdbc:postgresql://dpg-daakqhid0e5s73ddial0-a.ohio-postgres.render.com/social_vymp?currentSchema=public
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update